Make max script work with floats

diff --git a/bin/max b/bin/max
--- a/bin/max
+++ b/bin/max
@@ -1,7 +1,7 @@
 #!/bin/sh
-if [ $1 -gt $2 ]
-then
-    echo $1
-else
-    echo $2
-fi
+
+case $(echo "$1>$2" | bc -l 2>/dev/null) in
+    1) echo "$1";;
+    0) echo "$2";;
+    *) echo "Invalid arguments" >&2; exit 1;;
+esac
