./install deps will just install dependencies

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,12 +4,6 @@ BONCLAY_VER="1.1.0"
 DISTRO_NAME=$(lsb_release -ds 2>/dev/null \
     || cat /etc/*release 2>/dev/null | head -n1 | sed -n 's/^NAME="\(.*\)"/\1/p' \
     || uname -om)
-MODULE_PATTERNS=$@
-if [ "$MODULE_PATTERNS" = "" ]; then
-    INSTALLERS=$(find -name install.sh)
-else
-    INSTALLERS=$(find -name install.sh | grep $(echo $MODULE_PATTERNS | sed 's/^| / -e /g'))
-fi
 
 get_bonclay() {
     echo "Downloading bonclay... "
@@ -23,6 +17,11 @@ get_bonclay() {
     echo "Done"
 }
 
+install_symlinks() {
+    ! [ -f ./bonclay ] && get_bonclay
+    ./bonclay sync ./bonclay.conf.yaml
+}
+
 yes_no_prompt() {
     # Defaults to yes
     printf "$1 [Y/n] "
@@ -33,52 +32,90 @@ yes_no_prompt() {
     esac
 }
 
-! [ -f ./bonclay ] && get_bonclay
-./bonclay sync ./bonclay.conf.yaml
+install_all_deps() {
+    ALL_DEPS=""
 
-for installer in $INSTALLERS; do
-    NAME=$(dirname $installer | xargs basename)
-    echo "===== Installing $NAME ====="
-    # Source the installer to get $MAKEDEPENDS, $DEPENDS, and install()
-    # Do it in a subshell (the ()) so that they are lost on following iterations
-    # (i.e. so that different installers don't interfere with eachother)
-    ( . $installer
+    for installer in $INSTALLERS; do
+        ALL_DEPS="$ALL_DEPS $( . $installer; echo $MAKE_DEPENDS $DEPENDS )"
+    done
 
-    RUN_INSTALLER=true
+    sudo pacman -S --needed $ALL_DEPS
+}
 
-    if [ "$MAKEDEPENDS" != "" ] || [ "$DEPENDS" != "" ]; then
+
+main() {
+    install_symlinks
+
+    for installer in $INSTALLERS; do
+        NAME=$(dirname $installer | xargs basename)
+        echo "===== Installing $NAME ====="
+        # Source the installer to get $MAKEDEPENDS, $DEPENDS, and install()
+        # Do it in a subshell (the ()) so that they are lost on following iterations
+        # (i.e. so that different installers don't interfere with eachother)
+        ( . $installer
+
+          RUN_INSTALLER=true
+
+          if [ "$MAKEDEPENDS" != "" ] || [ "$DEPENDS" != "" ]; then
+              echo
+              echo "==> Installing required packages"
+
+              # Try to install with pacman and if that fails then detect the error
+              sudo pacman -S --needed --noconfirm $MAKEDEPENDS $DEPENDS || {
+                  echo "==> Error: Couldn't install required packages"
+                  if [ "$DISTRO_NAME" != "Arch Linux" ]; then
+                      echo "==> Required packages were found but current distro is not Arch Linux. "
+                      echo "==> The install script only knows how to install packages on Arch."
+                  fi
+                  echo "==> The required packages were:"
+                  echo "==> MAKEDEPENDS: "
+                  for dep in $MAKEDEPENDS; do echo "==> * $dep"; done
+                  echo "==> DEPENDS: "
+                  for dep in $DEPENDS; do echo "==> * $dep"; done
+
+                  # Can't use continue because we're in a subshell
+                  yes_no_prompt "Continue with installer for $NAME?" || RUN_INSTALLER=false
+              }
+          fi
+
+          if $RUN_INSTALLER ; then
+              type module_install >/dev/null 2>&1 && {
+                  echo
+                  echo "==> Running install script"
+                  module_install
+              }
+          fi
+
+        )
+
         echo
-        echo "==> Installing required packages"
+        echo "===== $NAME Done ====="
+        echo
+    done
+}
 
-        # Try to install with pacman and if that fails then detect the error
-        sudo pacman -S --needed --noconfirm $MAKEDEPENDS $DEPENDS || {
-            echo "==> Error: Couldn't install required packages"
-            if [ "$DISTRO_NAME" != "Arch Linux" ]; then
-                echo "==> Required packages were found but current distro is not Arch Linux. "
-                echo "==> The install script only knows how to install packages on Arch."
-            fi
-            echo "==> The required packages were:"
-            echo "==> MAKEDEPENDS: "
-            for dep in $MAKEDEPENDS; do echo "==> * $dep"; done
-            echo "==> DEPENDS: "
-            for dep in $DEPENDS; do echo "==> * $dep"; done
+# Find the command and shift it out of the parameters
+case $1 in
+    deps|help) COMMAND=$1; shift;;
+    *) COMMAND=main;;
+esac
 
-            # Can't use continue because we're in a subshell
-            yes_no_prompt "Continue with installer for $NAME?" || RUN_INSTALLER=false
-        }
-    fi
+# Find the installers matching the patterns provided
+MODULE_PATTERNS=$@
+if [ "$MODULE_PATTERNS" = "" ]; then
+    INSTALLERS=$(find -name install.sh)
+else
+    INSTALLERS=$(find -name install.sh | grep $(echo $MODULE_PATTERNS | sed 's/^| / -e /g'))
+fi
+if [ "$INSTALLERS" = "" ]; then
+    echo "==> No modules match $MODULE_PATTERNS"
+    echo "==> Stopping"
+    exit 1
+fi
 
-    if $RUN_INSTALLER ; then
-        type module_install >/dev/null 2>&1 && {
-            echo
-            echo "==> Running install script"
-            module_install
-        }
-    fi
-
-    )
-
-    echo
-    echo "===== $NAME Done ====="
-    echo
-done
+# Run the appropriate command
+case $COMMAND in
+    deps) install_all_deps;;
+    help) echo "Coming soon";;
+    *) main;;
+esac
